### ISSUE TITLE
&nbsp; is being printed in the report steps for triple quoted text in a step

### ISSUE THREAD

**Issue by kappa10j** [hrcorval/behavex#10]
For a step like the one below, 
Then The text is valid
  """
  This text is valid
  """
the report would show:
Given I am set up something
When I do something
Then The text is valid
  This&nbsp;&nbsp;text&nbsp;&nbsp;is&nbsp;&nbsp;valid

**Comment by kappa10j** [comment]
The character isn't showing up in the comment

I should just see: I understand that
![image](https://user-images.githubusercontent.com/11633310/155544731-4c48ce52-5966-41e1-ae5e-3ac5af02caff.png)

**Comment by anibalinn** [comment]
This issue has been fixed and will be part of next release

**Comment by kappa10j** [comment]
Great.  Looking forward to it!

**Comment by hrcorval** [comment]
Fixed in BehaveX v1.5.4: https://pypi.org/project/behavex/1.5.4/
