### ISSUE TITLE
Is it possible to get step wise screenshot for Selenium Test cases in HTML report

### ISSUE THREAD

**Issue by ayan199** [hrcorval/behavex#104]
Hi,

The screenshot shot is stored in context.evidepence_path. Is it possible to get the screenshot for each step in the HTML report.

**Comment by hrcorval** [comment]
Hi @ayan199 , totally agree. We will consider this in upcoming versions

**Comment by jackyxiao126** [comment]
> Hi @ayan199 , totally agree. We will consider this in upcoming versions

I also encountered this problem, looking forward to the latest version!!

**Comment by hrcorval** [comment]
Hi @ayan199. Finally, We have a draft library that allows you to attach screenshots to the HTML report. It is very easy to use.
Please take a look at the following: https://test.pypi.org/project/behavex-images/3.0.4/
We are already using it in some other projects and we find it to be very useful.
I hope it helps :)
