### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'logging_format'

### ISSUE THREAD

**Issue by Arwin-CTM** [hrcorval/behavex#106]
**Describe the bug**
I have installed behaveX and ran the command -> behavex -t @testtag --parallel-processes 4 --parallel-scheme scenario

Getting  -> AttributeError: 'Config' object has no attribute 'logging_format'. Can i please know how to resolve the issue

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hrcorval** [comment]
Hi @Arwin-CTM, We are not being able to reproduce this issue in latest BehaveX version. Are you still experiencing it?
Thanks!
