### ISSUE TITLE
Unable to execute scenario outline in parallel

### ISSUE THREAD

**Issue by korrapatisandhya** [hrcorval/behavex#108]
Describe the bug:
i am using selenium, python ,behave and behavex libraries in my project. 
My project is about to execute same steps for multiple input dynamically through command line parameters in that case i choose the scenario outline in behavex to use but i am unable execute the examples of scenario outline parallelly please let me know is behavex support parallel execution of scenario outline if so please provide an example.

**Comment by korrapatisandhya** [comment]
![image](https://github.com/hrcorval/behavex/assets/130272434/19b3aae7-9294-4227-b78f-973071a479b5)
![image](https://github.com/hrcorval/behavex/assets/130272434/78d0f7e1-cca7-472e-9b2d-6ed590cc2db9)
above is the sample code i am using to execute scenario outline in parallel execution but they are running in sequentially only

**Comment by hrcorval** [comment]
Fixed in latest Behavex version (v3.2.0). Please, let us know in case you see additional issues.
