### ISSUE TITLE
Keep browser open when running in parallel by feature

### ISSUE THREAD

**Issue by kappa10j** [hrcorval/behavex#11]
The tests would be very efficient if the browser could be kept open between runs.  The parallel is slow to an extent because the browser needs to relogin each time.

**Comment by hrcorval** [comment]
Sadly, the parallel execution is implemented with independent processes, not sharing anything across processes. So, it is not possible to synchronize activities, unless you do it with shared files or a similar mechanism. Keeping a browser session open across processes would require a custom implementation.
