### ISSUE TITLE
Background steps dont appear in the report

### ISSUE THREAD

**Issue by kappa10j** [hrcorval/behavex#112]
behavex 3.0.0

How can we include the steps of the background in the report?

**Comment by hrcorval** [comment]
Hi @kappa10j ,
    you can see the background steps next to the Scenarios header that is displayed when expanding a feature in HTML report:
    
<img width="292" alt="image" src="https://github.com/hrcorval/behavex/assets/7736350/0c91ceca-bf6a-4a5f-9a39-e752880aded7">

**Comment by hrcorval** [comment]
In case a background step fails for a specified scenario, the background steps are included into the scenario specificacion

**Comment by hrcorval** [comment]
We did an improvement in latest Behavex version, to fix some rendering issues in background steps. I suggest moving to the latest version

**Comment by kappa10j** [comment]
Thanks.  I'll check it out.
