### ISSUE TITLE
Jenkins Configuration for Behavex

### ISSUE THREAD

**Issue by crr1991** [hrcorval/behavex#122]
I have tried pip install in the local machine and it is working as expected.

Similarly tried to install the pip in Jenkins and showed the error as 
/home/jenkins/agent/workspace/on_Ignite-Core-Automation_space7@tmp/durable-8a1feb99/script.sh: behavex: not found

Does it work in the Jenkins??
If yes, please suggest, if am I missing anything over here.

When i install the behavex in Jenkins where am getting the below warning.

 WARNING: The script behavex is installed in '/home/jenkins/.local/bin' which is not on PATH.
17:07:32    Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Does it causing any issue??

Thanks in advance

**Comment by hrcorval** [comment]
Hi @crr1991. When installing BehaveX, it creates an executable file that is provided in the default binaries path associated to the Python distribution. If the binaries path is not in the PATH variable, it will no be found in console when typing "behavex".
This will happen for also for any binaries provided by other python libraries.
Regards,
