### ISSUE TITLE
How I can use behavex and webdriver 

### ISSUE THREAD

**Issue by hniia** [hrcorval/behavex#124]
I want to use webdriver to do UI testing I want to able screenshot and see it when I click evidence in the html report

**Comment by hrcorval** [comment]
Hi @hniia. Finally, We have a draft library that allows you to attach screenshots to the HTML report. It is very easy to use.
Please take a look at the following: https://test.pypi.org/project/behavex-images/3.0.4/
We are already using it in some other projects and we find it to be very useful.
Any feedback on that one will be really helpful.
I hope it helps :)
