### ISSUE TITLE
JUnit XML is always per feature

### ISSUE THREAD

**Issue by gridranger** [hrcorval/behavex#127]
**Describe the bug**
The README states: "By default, there will be one JUnit file per feature, unless the parallel execution is performed by scenario, in which there will be one JUnit file per scenario."

**To Reproduce**
`python -m behavex tests --parallel-processes 4 --parallel-scheme scenario`

**Expected behavior**
Having 2 JUnit XML files as I have 2 scenarios in my feature file.

**Screenshots**
![behavex](https://github.com/hrcorval/behavex/assets/28750410/46149952-818b-4b58-a7fb-8964551d7276)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: behavex==3.2.0

**Additional context**
the feature file's content:
```
@web @duckduckgo
Feature: Basic web search
  As a web surfer,
  I want to find information online,
  So I can learn new things and get tasks done.

  @webtest @firefox
  Scenario: More Basic DuckDuckGo Search
    Given the DuckDuckGo home page is displayed
    When the user searches for "dog"
    Then results are shown for "dog"

  Scenario: Other DuckDuckGo Search
    Given the DuckDuckGo home page is displayed
    When the user searches for "cat"
    Then results are shown for "cat"
```

PS: Great job on the library by the way :)

**Comment by hrcorval** [comment]
Hi @gridranger, We realize this is an issue in the documentation, as the junit files will always be generated at feature level. We will update the documentation accordingly. 
Thanks!!

**Comment by hrcorval** [comment]
Documentation has been updated, as indicated before.
