### ISSUE TITLE
Will html report support attach screenshot? that's very helpful.

### ISSUE THREAD

**Issue by jackyxiao126** [hrcorval/behavex#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hrcorval** [comment]
Hi @jackyxiao126, we have a draft library that allows you to attach screenshots to the HTML report. It is very easy to use.
Please take a look at the following: https://test.pypi.org/project/behavex-images/3.0.4/
We are already using it in some internal projects and we find it to be very useful.
I hope it helps :)
