### ISSUE TITLE
Modifying the output report generation path during runtime

### ISSUE THREAD

**Issue by satyasz** [hrcorval/behavex#129]
1. Whenever I run the features using 'behavex' cmd, it generates the output files in 'output' folder.

I want to modify the output path dynamically during runtime.
Is there a way to do so?

2. Also, whenever I run second time, it clears the output folder, generates the new output files.

I want to keep a backup of the previous output files.
Is there any option for that?

Thank you.

**Comment by hrcorval** [comment]
Hi @satyasz. Yes, You can change the output path by setting the following argument "-o". By default, the setting is implicitly set as "-o output", so you can change it to something like "-o output2" and the execution results will be stored in the ./output2 folder.
I hope it helps :)
