### ISSUE TITLE
In html report show testcase execution start time and end time

### ISSUE THREAD

**Issue by komaljamodkar** [hrcorval/behavex#130]
With behavex execution with tags, would be possible to show total execution time of all scenario on top
Now, its displaying individual scenario duration. And total in bottom
Start date time :10/07/2024 06:00.00
end date time : 10/07/2024 06:00:2.9
Total duration of scenario execution : 2.9 sec on top of screen
![IMG_20240710_195503](https://github.com/hrcorval/behavex/assets/48888350/080fe0e7-9f5c-4a3a-8c49-9209dc28402a)

**Comment by hrcorval** [comment]
Hi @komaljamodkar , of course we can do it, the only concern about this, is that start time and end time will be related to the time zone where the tests are being executed, so if you are running in the cloud, it might not be the same as you local time

**Comment by hrcorval** [comment]
Hi @komaljamodkar, We have released a new library version (v4.0.2) with the requested improvements (among multiple other enhancements/fixes):
![image](https://github.com/user-attachments/assets/0d658813-618a-487e-9620-e05fa07c9dc7)

You can see the information in the upper right side of the execution report.
Also, In case you need to provide additional info, you can set the ENVIRONMENT_DETAILS environment variable, with comma separated strings that will be parsed and shown in the tooltip (as you can see in the screenshot).
Thanks a lot for reporting this improvements!
I hope it helps
