### ISSUE TITLE
behavex-images UNKNOWN in pip-licenses

### ISSUE THREAD

**Issue by dipukrishnan** [hrcorval/behavex#137]
With the latest changes we are get license error for behavex-images

**To Reproduce**
1. Install behavex 3.3.o version
2. pip install pip-licenses
3. Result

 Name                           Version            License                                                                                                         
 behave                         1.2.6              BSD License                                         
 behavex                        3.3.0              MIT License                                         
 behavex-images                 3.0.5              UNKNOWN 

**Expected behavior**
Should pass pip license check

**Desktop (please complete the following information):**
 - Version [3.3.0]

**Comment by hrcorval** [comment]
Hi @dipukrishnan , you are right, I have released a new version of the behavex-images library with the corresponding license (v3.0.6). 
I hope it works! 
Thanks!

**Comment by dipukrishnan** [comment]
It works, Thank you
