### ISSUE TITLE
Error while using progress bar on Jenkins

### ISSUE THREAD

**Issue by livefrommin** [hrcorval/behavex#139]
**Describe the bug**
When trying to use argument "--show-progress-bar" it shows the error:
`Traceback (most recent call last):
  File "/usr/local/bin/behavex", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/behavex/runner.py", line 72, in main
    exit_code = run(args)
  File "/usr/local/lib/python3.10/dist-packages/behavex/runner.py", line 121, in run
    return launch_behavex()
  File "/usr/local/lib/python3.10/dist-packages/behavex/runner.py", line 202, in launch_behavex
    execution_codes, json_reports = launch_by_feature(
  File "/usr/local/lib/python3.10/dist-packages/behavex/runner.py", line 350, in launch_by_feature
    global_vars.progress_bar_instance = _get_progress_bar_instance(total_elements=total_features)
TypeError: _get_progress_bar_instance() missing 1 required positional argument: 'parallel_scheme'`

Command that I'm using: `behavex -t $FEATURE_FILES --parallel-processes 16 --parallel-scheme feature --show-progress-bar`

Have found the cause of it:
<img width="807" alt="Screenshot 2024-09-03 at 14 55 57" src="https://github.com/user-attachments/assets/9046bf50-eb51-4492-8bb2-5847049d844b">
When you run with scheme "scenario", this attribute is going there.
![Screenshot (2)](https://github.com/user-attachments/assets/c9e7b6a5-ddbf-4665-bff2-4194f67fe2ee)
And if you run with scheme "feature" - it's not used.

**Comment by hrcorval** [comment]
Hi @livefrommin , the issue has been fixed in recently released library v4.0.2 (https://pypi.org/project/behavex/)
Thanks a lot!
