### ISSUE TITLE
Implemented behavex in a small framework setup

### ISSUE THREAD

**Issue by salunkhe-ravi** [hrcorval/behavex#14]
Thanks @hrcorval for developing this amazing module for behave.
Was needing the parallel execution feature in behave since ages.

I tried implementing behavex into a framework which might be of some help...let me know with your thoughts!

https://github.com/salunkhe-ravi/behavex-boilerplate-framework

**Comment by hrcorval** [comment]
This is great Ravi! I'll review it, and if you agree, we can leave it as a sample startup project, linked from documentation.

**Comment by salunkhe-ravi** [comment]
This is still in draft though, will spend sometime adding some more examples for web as well as API automation which would help anyone to get started with behavex!.

**Comment by hrcorval** [comment]
Thanks a lot Ravi, it looks very good, I've added a link as a contribution in release notes in the upcoming BehaveX version

**Comment by hrcorval** [comment]
Release Notes: https://github.com/hrcorval/behavex/blob/master/CHANGES.rst

**Comment by salunkhe-ravi** [comment]
Thanks for the acknowledgement @hrcorval ! This is really motivating :)
Will continue to contribute the "boilerplate" project making it more mature and maintained.

**Comment by vsriaditya-numerator** [comment]
@salunkhe-ravi, @hrcorval, How do I implement Allure Reports using behavex, because the -f tag for formatting doesn't work! Please advise!
