### ISSUE TITLE
behavex 4.0.2 generates invalid failure XML

### ISSUE THREAD

**Issue by aconti-ns1** [hrcorval/behavex#144]
**Describe the bug**
XML files generated by behavex contain invalid `<failure>` tags: the `type` attribute is unquoted and the `CDATA` is empty.

**To Reproduce**
1. Run behavex 4.0.2 with failing tests (see **Additional Context** for my minimal configuration)
2. `behavex -o reports`
3. Check the XML in `reports/behave/`
4. Observe the `<failure>` tag:
```
<failure type=Exception message=''>
    <![CDATA[  ]]>
</failure>
```

**Expected behavior**
The `<failure>` tag should contain a quoted value for the `type` attribute and the failing test step information should be contained in the `CDATA`:
```
<failure type="Assertionerror" message=''>
    <![CDATA[ Failing step: -- OMITTED OUTPUT -- ]]>
</failure>
```

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 22.04.4), macOS (14.4)
 - behavex Version 4.0.2

**Additional context**
I have confirmed this is not related to behave, I have invoked behave with behavex installed at both 3.2.0 and 4.0.2 and behave generates valid XML in both cases.

I have a minimal configuration which will reproduce the issue:

`features/steps/steps.py`
```python
from behave import step

@step("the test fails")
def fail_step(context):
    assert(False), "FAIL!"
```

`features/sample.feature`
```gherkin
Feature: Sample test
  Scenario: A failing scenario
    Given the test fails
```

**Comment by hrcorval** [comment]
Hi @aconti-ns1, we have fixed this issue in latest version: https://pypi.org/project/behavex/4.0.4/
We hope it helps.

**Comment by aconti-ns1** [comment]
Awesome, thanks so much!
