### ISSUE TITLE
Is it possible to run the tests output in failed.txt and have those results incorporated into the existing results html?

### ISSUE THREAD

**Issue by kappa10j** [hrcorval/behavex#15]
It would be great to be able to rerun a failed test or at least be able to run the failed tests and incorporate it into the existing log.

**Comment by hrcorval** [comment]
We currently have the "AUTORETRY" tag, that if it is added to any test scenario, it will cause the test to be re-executed if it failed. The results of the re-execution will be posted in the test report. 
We don't have yet an argument that would allow re-running any failing test, but we can consider having it in a short term behavex version

**Comment by kappa10j** [comment]
Will it work on a feature?  I'd want to just retry all.

Just tag @autoretry ?

**Comment by hrcorval** [comment]
Yes, it will work. I'll be adding @AUTORETRY to documentation

**Comment by kappa10j** [comment]
Is it possible to just sorry a global auto retry of sorts?  Via cmd line
argument maybe.  And also use the number of retries fixed at 1?

**Comment by hrcorval** [comment]
Yes, it is possible, so I'll consider adding this feature asap :)

**Comment by writetomaha** [comment]
This feature would be really helpful. can you please consider this feature as well

**Comment by hrcorval** [comment]
The AUTORETRY feature was added considering multiple retries: AUTORETRY_3, AUTORETRY_4 .... where the suffix number represents the number of retries to perform when the related scenario fails

**Comment by hrcorval** [comment]
Information added to the documentation.
I hope it helps :)
