### ISSUE TITLE
IncludePathsMatch issue when features path isnt supplied

### ISSUE THREAD

**Issue by iamkenos** [hrcorval/behavex#153]
**Describe the bug**
I think this bit of the code will evaluate differently for windows machines. this bug has been hiding here since version 3.x i think.
![image](https://github.com/user-attachments/assets/0d9a24a2-42f6-44b5-af5f-0fd7598e2fa3)

- I'm running a windows machine
- So what happens is, when i run behavex in parallel mode without supplying a features path argument.
- Internally, `FEATURES_PATH` will resolve to a default value joining the absolute `BEHAVEX_PATH` and `features`:
  - in windows, this is most likely gonna be under `DRIVE:\foo\bar\path\features` - notice the `:` right after `DRIVE`

Result: 
- i get 0 tests when i run:
  - `behavex -t one -t this --parallel-processes 2 --parallel-scheme scenario`
  - ![image](https://github.com/user-attachments/assets/1617e970-3bf3-47c9-9138-15371ed9ff43)
- but it works when i do:
  - `behavex -t one -t this --parallel-processes 2 --parallel-scheme scenario features`, which is essentially the same.
  - ![image](https://github.com/user-attachments/assets/55bc1e0c-6112-4cb8-b971-1bc594bf50ce)

Note that `behavex -t one -t this` works just fine.

**Desktop (please complete the following information):**
 - OS: Windows

I'd be happy to help with the fix but I'm not really sure what the check for `:` is for.

**Comment by hrcorval** [comment]
Hi @iamkenos. First of all, thank you for taking time for reporting that kind of issues, it is very important for us to tackle the bugs as soon as possible. We are working on fixing this issue, and we will have a new release available very soon, most probably early next week. 
Keep you posted on this.

Thanks!

**Comment by hrcorval** [comment]
Your solution seems to be working, to I have tagged the PR as fixed. Thanks!!
