### ISSUE TITLE
Can we participate in hacktoberfest?

### ISSUE THREAD

**Issue by iamkenos** [hrcorval/behavex#154]
It's that time of the year!

Just wondering if the maintainers of this project are open to participating in hacktoberfest?
https://hacktoberfest.com/participation/

I've been actively using behavex for the past 3 months and i've been participating in discussions here and there.
I've just recently cloned the code and symlinked it to my local automation project so i can debug better.

I'm open to contributing to this repo for issues I may find and coincidentally, i'm also looking to participate in hacktoberfest.
Thought maybe we can participate in the event and people / users (such as myself) to contribute.

Hope to hear back!

**Comment by hrcorval** [comment]
Hi @iamkenos , I'm very glad to see you would like to participate in the hacktoberfest, I love open source projects. I hope you can register :)
Of course, you can take advantage of BehaveX and provide PRs with enhancements/fixes to get the hacktoberfest digital badge unlocked. I totally support you on this.
Best wishes!

**Comment by iamkenos** [comment]
thanks! there are some requirements to participate and for PRs to count:
- can you help add the hacktoberfest label in the repository please? this can be done from the repo's `About` settings then `Topics` field: 
![image](https://github.com/user-attachments/assets/c9c4b361-5298-40a4-9ed0-c066917e901e)
![image](https://github.com/user-attachments/assets/6b100510-ff45-4641-b2a6-8b72f3b77269)

- also, approved PRs will need to be marked by `hacktoberfest-accepted` tag. would very much appreciate if you can add the tag here please. https://github.com/hrcorval/behavex/issues/153

cheers!

**Comment by hrcorval** [comment]
I did both, added the topic and tagged the PR :)
Please, let me know about anything else you might need.
