### ISSUE TITLE
Question: Parallel Scheme

### ISSUE THREAD

**Issue by iamkenos** [hrcorval/behavex#157]
**Is your feature request related to a problem? Please describe.**

**Given** I have 2 feature files, having 2 scenarios each
**And** each scenario has 10 examples each (total 40 unique examples)

What would happen when I run `behavex` in `parallel-scheme=scenario` and `parallel-scheme=feature`?

**Context:** Im trying to upgrade from `behavex v1.6` to the latest version.

I ran some local benchmarking and realized the following:
 - in `v1.6`, `parallel-scheme=scenario` works on `scenario` level. **im guessing** if you have 1 feature having 2 scenarios with 10 examples each, then **2** threads will be spun up to run the tests, **1** for each scenario. these threads would then work through each example in the scenario.
 - in the latest version, it would seem like `parallel-scheme=scenario` works on `example` level. **im guessing** if you have 1 feature having 2 scenarios with 10 examples each, then **20** threads will be spun up to run the tests, **1** for each example - yielding a much faster execution time.

Now i want to confirm whether if I use `parallel-scheme=feature` on the latest version:
 - would it spin up 2 threads - 1 for each feature as given on my initial example at the top of the post?
 - or would it spin up 4 threads - 1 for each scenario inside the feature files

I'm raising the question purely to understand how it works - because i would think `parallel-scheme=scenario` **should** work on `scenario` level and not on `example`. having the ability to run it on `example` level is very useful but can introduce undesirable issues when we dont know how it works (rate limitting issues during api calls for instance)

i feel the current behavior of  `parallel-scheme=scenario` is more fitting for  `parallel-scheme=example` but that's a topic for another day perhaps.

For now, really just want to understand to behavior.

**Comment by hrcorval** [comment]
Hi @iamkenos. You did very good questions :)
Regarding `parallel-scheme=scenario` you are right, in latest version, the examples that are part of a scenario outline are also executed in parallel, and this differ to the behavior in v1.6. 
The change was done based on requirements from users to split the examples across the parallel sessions. However, considering your question and your expectations, we might need to consider another execution argument to run the scenario outline examples in serial mode or in parallel. That implementation would not be easy at all to implement, as we cannot change the current behavior of the `parallel-scheme=scenarios` (that is currently involving running the examples in parallel), so we need to analyze if we can add another argument for it.

Going over `parallel-scheme=feature`, each parallel process will pick up a feature file, and everything within the feature file will run in serial mode in the assigned process. So, your first assumption ("would it spin up 2 threads - 1 for each feature as given on my initial example at the top of the post?") is the correct one.


Also, your questions

**Comment by iamkenos** [comment]
thanks for clarifying @hrcorval !
