### ISSUE TITLE
[Help] While using behavex images getting error

### ISSUE THREAD

**Issue by vibincwilson** [hrcorval/behavex#180]
ERROR:root:[behavex-images] The provided binary is not a valid image, or could not be converted to PNG: module 'numpy' has no attribute 'float'.
      `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
      The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
          https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

I have library numpy 2.1.3

**Comment by prasanmgc** [comment]
@vibincwilson Until the new version 4.0.9 which ideally have numpy updated. use the below to proceed further.

Add np.float = float above the below line in your environment.py.

image_attachments.set_attachments_condition(context, AttachmentsCondition.ALWAYS)

Hope this helps :)

**Comment by hrcorval** [comment]
Hi @vibincwilson, thanks for posting this issues and provide details about the fix. As you mention, there is an incompatibility issue with numpy.float. We have released a draft package with the fix, that it is ready to install at: https://test.pypi.org/project/behavex-images/3.0.8/
We will do more testing on it and perform a formal release soon.
Thanks!

**Comment by hrcorval** [comment]
The new package has been tested and officially released: https://pypi.org/project/behavex-images/3.0.8
Thanks!
