### ISSUE TITLE
pass a multiprocessing communication to behave

### ISSUE THREAD

**Issue by lpegoraro** [hrcorval/behavex#21]
Firstly, thanks for this!

I am testing with checking port availability and I wanted to fetch new ports and somehow communicate that specific port is not in the pool anymore.

I am trying with a few mechanisms to control that better, what do you recommend?

**Comment by hrcorval** [comment]
Hi Luiz,
     The best mechanism I have found so far to share information is by using common files that are accessible across parallel instances. As parallelism is implemented at process level (instead of threads), there are no shared variables.
On the other way around, if there is any shared information you would like to set before launching the tests, and make it accessible to all parallel instances, you can declare environment variables. So when the parallel processes are launched, the declared environment variables are accessible from each individual process.
Also, you have the possibility of using a lightweight database that is shared across parallel instances, but maybe this is a complex approach if you are just thinking on sharing few data.

I hope it helps!

Hernan
