### ISSUE TITLE
Is there a possibility to organize our folder structure in our own way?

### ISSUE THREAD

**Issue by prsnth89** [hrcorval/behavex#34]
Currently my testcase folder structure is and this is working fine
features
   test1
       testcase1.feature
    test2
       testcase2.feature
     environment.py
    pages
        loginpage.py
        homepage.py

Now i have rearranged to the below folder structure but this is not working, please let me know if we have the option to rearrange folder structure as per developer wish

test
    features
             test1
                   testcase1.feature
              test2
                   testcase2.feature
      environment.py
pages
    loginpage.py
    homepage.py

**Comment by hrcorval** [comment]
Hi @prsnth89, folders structure for features and steps modules have to be set according to the "behave" framework conventions (which is the base framework for this wrapper). Considering this:

- All feature files have to be set inside any folder structure within the "features" folder (in project root folder)

- All the steps modules have to be set inside any folder structure within the "steps" folder (in project root folder).

Hope it helps :)
