### ISSUE TITLE
Configurable path to features directory

### ISSUE THREAD

**Issue by Hejvi** [hrcorval/behavex#42]
**Is your feature request related to a problem? Please describe.**
I tried to run behavex outside the test directory and every time I got the information: `"features" folder was not found in current path...`. Flag `-ip` does not help with finding the path. Even manually setting the environment variable `FEATURES_PATH` does not help because in the __init__ file this variable is overwriting due to: `os.environ['FEATURES_PATH'] = os.path.join(os.getcwd(), 'features')`

**Describe the solution you'd like**
It would be nice to set path to the feature directory in the command run, for example:
`behavex directory_a/directory_b/features`

**Describe alternatives you've considered**
Allow setting manually the environment variable `FEATURES_PATH`

**Additional context**
No additional context

**Comment by hrcorval** [comment]
Hi @Hejvi , I'll take a look at the implementation and find an approach that help on setting a test directory. Leaving this open until a solution is provided

**Comment by hrcorval** [comment]
The solution implies:
- Adding a new positional argument to behavex to receive the Feature directory, file or file location
- Adapt mechanism to run parallel features/scenarios to the new positional argument

**Comment by hrcorval** [comment]
Implementation fixed and pushed to branch https://github.com/hrcorval/behavex/tree/release_2.0
