### ISSUE TITLE
How is it possible to add a screenshot for evidence?

### ISSUE THREAD

**Issue by andriy-cyber** [hrcorval/behavex#43]
Was trying to embed made screenshot into report but no luck. Is it possible? If yes then how? Can you update readme file with this information?

**Comment by p-cote** [comment]
Interested in this feature too :)

**Comment by asket888** [comment]
Me too. It is very essential especially because of Allure not supported by behavex

**Comment by yortunoc** [comment]
It is very important to reports

**Comment by hrcorval** [comment]
Hi! We are going to add this capability to the backlog, so screenshots can be easily added to the report.
Regards

**Comment by igormoraisn** [comment]
right now you can attach screenshots using the `context.evidence_path` variable

`driver.get_screenshot_as_file(context.evidence_path + 'login_scenario.png')`

**Comment by ThamodrenSinniah** [comment]
As @igormoraisn mentioned, you can save a screenshot into the path provided by `context.evidence_path`.
Here is how to use it in the `after_scenario` fixture.

```
screenshot_name = f'{scenario.name}_{datetime.now().strftime("%Y_%m_%d__%h_%m_%s")}.png'
context.driver.save_screenshot(f'{context.evidence_path}/{screenshot_name}')
```

Open your `report.html` and you should be able find the screenshot in the scenario.

Keep in mind, just adding the code above will save a screenshot for **ALL** scenarios. If you want only a screenshot saved when a scenario fails, you could add the above code inside an `if` block that checks if the scenario failed.

```
def after_scenario(context, scenario):
  if scenario.status == 'failed':
    screenshot_name = f'{scenario.name}_{datetime.now().strftime("%Y_%m_%d__%h_%m_%s")}.png'
    context.driver.save_screenshot(f'{context.evidence_path}/{screenshot_name}')
```

**Comment by anibalinn** [comment]
`context.evidence_path` can be used by the moment to store the screenshots until a better solution is provided (we are working on that)

Thanks!
