### ISSUE TITLE
if more features are run it will fail few and it will take too long to generate the report

### ISSUE THREAD

**Issue by gaju99** [hrcorval/behavex#47]
**Describe the bug**
I ran  behavex -t @myTag --log-capture  --parallel-processes 20 --parallel-scheme feature -o AllureReports
i had about 45 features with tag as @mtTag, when it was done executing, it failed 7 out of 45. i executed 7 failed individually it passes.

Also it takes a longer time to generate the reports. Any suggestion ?

**Comment by hrcorval** [comment]
Hi @gaju99 , which kind of error are you getting in failing features? 
Talking about performance, sometimes parallel executions stress the systems under test. May be problem be related to that.
On the same line, 20 parallel processes might require lot of CPU and memory, depending on the characteristics of the automated implementation you are executing, and that might also be overloading the system. Might the problem be related to anything of that?
Regards

**Comment by hrcorval** [comment]
Please, reopen this question if you consider this one was not properly answered. Thanks!
