### ISSUE TITLE
Behavex command not working as per documentation

### ISSUE THREAD

**Issue by jigisha9** [hrcorval/behavex#54]
@hrcorval  @balaji2711 @Remox129  @anibalinn 
Behavex command not working as per documentation...pls. advise

tried all possibilities:

behavex -ip ./tests/wms/autotest/web/features -t InventorySyncVarianceConfiguration_ICN --color -o .
behavex -t InventorySyncVarianceConfiguration_ICN --color -o . 
behavex -t @InventorySyncVarianceConfiguration_ICN --color -o .  
behavex -t @InventorySyncVarianceConfiguration_ICN 

![image](https://user-images.githubusercontent.com/7517067/204388378-f11a69dc-5bbf-4826-9c1b-c968fa6fd067.png)

**Comment by balaji2711** [comment]
Hi @jigisha9,

I have tried and it's working as expected. PFA for the screenshots.

**Command 1** - behavex -tWeb --color

![image](https://user-images.githubusercontent.com/15344129/204461165-b31cc266-b450-4c1c-9adc-dbef38a01ff4.png)

**Command 2** - behavex -t@Web --color

![image](https://user-images.githubusercontent.com/15344129/204461403-ecc9c9b4-9c21-469b-b9ff-634ac2b8dbb8.png)

Please don't give any space between -t and the tag name.

**Example:**             
            behavex -t@TAGNAME or behavex -tTAGNAME

**Comment by jigisha9** [comment]
Thanks @balaji2711 @anibalinn  for getting back...
so now  `behavex -t@TAGNAME or behavex -tTAGNAME` works 

although behave.ini is not respected. I have paths and parameters defined in behave.ini which should be respected when we run using behavex. How to make that happen?

![image](https://user-images.githubusercontent.com/7517067/207100443-2a2895f7-3c04-42be-ae22-45a8a15f2485.png)

![image](https://user-images.githubusercontent.com/7517067/207100849-4b38f7ea-de42-4c62-a9d6-3f37936685fa.png)

**Comment by hrcorval** [comment]
Hi @jigisha9, you are right, not all the parameters in behave.ini are being respected, we are way behind on suporting the .ini file. As soon as we have more bandwidth we are going to focus on that incompatibility issue.
Regards

**Comment by hrcorval** [comment]
New documentation will be povided with release 3.3.0.
