### ISSUE TITLE
How to add arguments to main method while running python command?

### ISSUE THREAD

**Issue by abdullahsaf** [hrcorval/behavex#55]
I am running behave using python instead of command line. Behave implementation have a main method that I imported which arguments such as: 
```behave.__main__.main(args=['-t @Tag1'], '--no-skipped')```
Is there a way I can add arguments to **behaveX** main module so I can use it from python runner?

Also I don't see `-no--skipped` argument in [list of supported arguments](../#supported-behave-arguments). 
>"There might be more arguments that can be supported, it is just a matter of adapting the wrapper implementation to use these."

Is it possible to add this argument? If so, how?

**Comment by hrcorval** [comment]
Hello @abdullahsaf, I see you can call the BehaveX implementation from python call in the following way:
`behavex.runner.run(args)`

So you can have an implementation like:

def run_behavex():
    args = sys.argv[1:]
    exit_code = behavex.runner.run(args)

I hope it helps

**Comment by hrcorval** [comment]
Regarding the` -no--skipped` argument, we need to analyze if it can be supported, so let me check about this.
Thanks!
