### ISSUE TITLE
Use behave.ini

### ISSUE THREAD

**Issue by robbrad** [hrcorval/behavex#56]
I have specified a path where my features are in behave.ini

Behavex ignores this. Id like to give Behavex a directory or path where my features reside

**Comment by anibalinn** [comment]
Hi @robbrad, we will increase the priority on that implementation, as there have been more requests on this. Hope to have this ready asap.

**Comment by robbrad** [comment]
@anibalinn Do you know if there is another way in the short term to specify the location of a feature file for behaveX

My current tests take 10 mins and could easily be made parallel (it uses Scenario Outline and an example table currently and runs 1 by 1)

**Comment by anibalinn** [comment]
Now it is possible to specify the paths where the feature files are located. Please, send me your feedback about the new functionality, just to understand if it meets your expectations.
Improvements in behave.ini are still pending,
Fix released in version 3.0.0: https://pypi.org/project/behavex/3.0.0/
branch [release_3.0.0](https://github.com/hrcorval/behavex/tree/release_3.0.0)
Thanks!
