### ISSUE TITLE
behave.context global variables are not working in parallel execution

### ISSUE THREAD

**Issue by asket888** [hrcorval/behavex#58]
In my application under test it is impossible to run two browser sessions with the same user (security reason). So to run tests in parallel I have to use pull of users. 

The solution is usual: 
1) set pull of users to global variable as a dict() (e.g: context.users)
2) pick one user from the pull of users
3) remove this user from the global variable
4) run test
5) add user after test execution to common pull

However it is not working with behave context. Is there any solution to use common variables for parallel tests execution in behavex?

**Comment by hrcorval** [comment]
Hi @asket888, as parallel executions are performed in terms of parallel processes, one of the ways to share information across all processes is to set environment variables when launching the execution. Something like:
```
export <var_name> = <var_value>
behavex <arguments>
```
Then, you can use the environment variables within the parallel processes.

Also, you can use files to share information across processes, and in this case you can update the information in files at runtime having the other processes getting the updates.

Hope this helps :)

**Comment by asket888** [comment]
Hi @hrcorval, using files to share information across processes works for me.

Thank you so much for the hint! :)
