### ISSUE TITLE
Unable to attach evidence log file in the report while running it in docker container. 

### ISSUE THREAD

**Issue by Joseph-Maduram** [hrcorval/behavex#6]
Hi, 
We are running our automation inside docker. 
All reports are working fine except the evidence. 
Evidence is generated in the backend, but link not appears and not linking the evidence  file. 
But same script works fine for non docker environment. 
Please help.

**Comment by hrcorval** [comment]
> Hi, We are running our automation inside docker. All reports are working fine except the evidence. Evidence is generated in the backend, but link not appears and not linking the evidence file. But same script works fine for non docker environment. Please help.

Hi Joseph, maybe there is a misunderstanding with the evidence path, as it only stores files that you have copied from sources into the specified path. We have not tried doing remote linking, as it is not implemented. Maybe we can consider this as a TODO

**Comment by hrcorval** [comment]
cannot reproduce after several tries

**Comment by hrcorval** [comment]
Please, let us know if you continue experiencing this issu in version 1.5.4
