### ISSUE TITLE
Add supported Behave arguments to run Allure Report

### ISSUE THREAD

**Issue by asket888** [hrcorval/behavex#61]
**Is your feature request related to a problem? Please describe.**
Nowadays Allure report is quite a standard for automated tests reports (https://github.com/allure-framework).
To run E2E tests with behave and Allure report, I have to use the following command
`behave --format allure --outfile allure-report`

**Describe the solution you'd like**
Is it possible to add `-f, --format` and `-o, --outfile` arguments to be supported by behavex?

**Describe alternatives you've considered**
Currently the only alternative with behavex is to use Junit reports which are quite ugly and doesn't support screenshots attaching

**Comment by anibalinn** [comment]
Hi @asket888. Sadly, BehaveX cannot reuse the functionality to generate allure reports, as when running in parallel there is no easy way to concatenate the results from parallel processes into one report. Instead, BehaveX generates its own html report, that is published into the output folder (report.html).

Regards,
Hernan
