### ISSUE TITLE
Is there a way to generate behavex report based on feature? If a feature has 20 scenarios then I should see one test case passed

### ISSUE THREAD

**Issue by PriyadarshiniSelvaraju** [hrcorval/behavex#63]
behavex -t @abc --parallel-processes 3 --parallel-scheme feature  - Running this behavex cmd is not generating the reports by feature level.

Behavex report not showing the test case execution for feature level.Is there a way to generate total cases by feature?

My feature files has lot of workflow. Each feature has 10 scenario . Instead of generating report for every scenario. I just want to generate one test case passed. 

Is there a way to do it using behavex?

**Comment by wuyangke** [comment]
At most projects, user will consider a scenario as a test case. You can refer to the formal gherkin feature file.
https://behave.readthedocs.io/en/latest/gherkin.html#scenarios
https://cucumber.io/docs/gherkin/reference/
https://docs.specflow.org/projects/specflow/en/latest/Gherkin/Gherkin-Reference.html

**Comment by anibalinn** [comment]
Hi @PriyadarshiniSelvaraju , this is not possible at the moment, as BehaveX generates only one report per execution. If you need to have reports at feature level, you should perform one execution for each feature.

I hope it helps
