### ISSUE TITLE
Is there a way to show the total number of features in the behavex report?

### ISSUE THREAD

**Issue by PriyadarshiniSelvaraju** [hrcorval/behavex#65]
Is there a way to show the total number features in the behavex report?

**Describe the solution you'd like**
Right now behavex report is showing total scenarios. Is there a way to show the total features?

**Comment by anibalinn** [comment]
Hi @PriyadarshiniSelvaraju . Thanks for posting this improvement. We will consider adding it in following BehaveX version.

Regards,

**Comment by anibalinn** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/87445484/232935566-bca81bd4-61bb-4d41-bff9-66364d397347.png">

**Comment by anibalinn** [comment]
Changes delivered in latest release (v2.0.1)
