### ISSUE TITLE
Not able to run the tests from root directory using behaveX which is possible using behave

### ISSUE THREAD

**Issue by HarikrishnanVK** [hrcorval/behavex#66]
**Describe the bug**
I have a directory that has different sub folders where one of them has features and tests related to Behave. 

Using Behave package, I can run my feature pointing to my sub folder as per below command..
behave behaveSample/features --tags=dropdownTest

But when i try to do the same using behaveX wrapper, it is not finding my features and throwing error as unrecognized arguments.
![image](https://user-images.githubusercontent.com/47863936/218679145-2ead9d15-68c4-4829-a7ab-71afa29ff015.png)

I couldn't find anything from documentation about how to set the path to features folder via behaveX CLI. 
Plz help me on this.

**To Reproduce**
1. Create a directory
2. Have your features inside a sub directory/folder
3. Now try to run the test using behaveX wrapper. "You will find a error that features folder is not part of the directory"
4. Now try mentioning the sub directory followed by behaveX command before tags (-t) flag, you will seen an error as unrecognized argument.

**Expected behavior**
BehaveX should able to find the features directory located inside sub directories or at least there should be a way to mention the directory path like in behave.

**Screenshots**
With behave where features are found:
![image](https://user-images.githubusercontent.com/47863936/218680949-7720fe77-9301-4d57-b016-7a7eeb62dd04.png)

With behaveX where features are not found:
![image](https://user-images.githubusercontent.com/47863936/218681318-c3573f4e-24b2-46bd-a321-2601e6094c6d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser : Chrome
 - Version : BehaveX 1.6.0

**Comment by anibalinn** [comment]
Hi @HarikrishnanVK , thanks for posting this issue. We are currently working on improvements to support indicating the features path as part of the execution arguments (and not assume the features folder is always located in root execution directory). We will have that implementation ready soon (cannot provide an ETA yet, sorry)

Regards,
Hernan

**Comment by hrcorval** [comment]
Hi @HarikrishnanVK, We have applied the fix in https://github.com/hrcorval/behavex/tree/release_2.0.0
It will be released pretty soon.

Regards,

**Comment by anibalinn** [comment]
Changes already implemented in latest release (v2.0.1)
