### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by T3-JacksonBush** [hrcorval/behavex#69]
There is a typo in the readme https://github.com/hrcorval/behavex#parallel-test-executions

In two of the example sections:

`--parallel-schema` should be `--parallel-scheme`

Also in the dry run section https://github.com/hrcorval/behavex#additional-behavex-arguments

`teh` should be `the`

:)

**Comment by hrcorval** [comment]
Thanks a lot @T3-JacksonBush, I have applied the fix in https://github.com/hrcorval/behavex/tree/release_2.0.0
We appreciate your contribution.

Regards,
Hernan

**Comment by anibalinn** [comment]
Changes already implemented in latest release (v2.0.1)
