### ISSUE TITLE
No matching distribution found for behavex

### ISSUE THREAD

**Issue by ed-sparkes** [hrcorval/behavex#7]
Cant install this 

`pip install behavex` results in 

ERROR: Could not find a version that satisfies the requirement behavex (from versions: none)
ERROR: No matching distribution found for behavex

**Comment by kappa10j** [comment]
make sure you running the cmd prompt as an admin

**Comment by hrcorval** [comment]
Hi @ed-sparkes , I was trying to reproduce this issue, but I could not generate the conditions to do it. Are you still having this issue? I think it might be due to the supported python versions, but just guessing.
