### ISSUE TITLE
Document what is the difference with behave-parallel

### ISSUE THREAD

**Issue by dgutson** [hrcorval/behavex#72]
Please add some documentation (FAQ?) explaining the difference between BehaveX and behave-parallel (eg https://github.com/hugeinc/behave-parallel or one of its other forks).
Also, a section telling "When you should use BehaveX" would be useful.

**Comment by hrcorval** [comment]
BehaveX and parallel-behave are both extensions to the Behave BDD testing framework, but they differ significantly in scope and functionality. BehaveX can be seen as a comprehensive testing framework built on top of Behave, offering not only parallel execution capabilities but also a wide range of additional features such as advanced reporting, test management, and execution control options. In contrast, parallel-behave is more focused, primarily aiming to add parallel execution functionality to the existing Behave framework without significantly altering its core structure or adding extensive additional features. While both tools enhance Behave's capabilities, BehaveX provides a more feature-rich and integrated solution, whereas parallel-behave offers a more targeted approach to parallelism.

| Feature | BehaveX | parallel-behave |
|---------|---------|-----------------|
| Parallel Execution | By feature or scenario; configurable number of processes | Primarily by feature |
| Installation | Via pip: pip install behavex | Requires modifying behave runner |
| Usage | behavex command | Custom command |
| Customization | Extensive configuration options and tags | Limited to command-line arguments |

Some additional capabilities provided by BehaveX:

- Comprehensive HTML, JSON, and JUnit reporting with detailed metrics, logs, and evidence attachments
- Test muting with @MUTE tag
- Enhanced dry run functionality with HTML report generation
- Auto-retry for failing scenarios with @AUTORETRY tag
- Configurable console progress bar
- Built-in support for attaching images and evidence to reports
- Detailed execution metrics including automation rate, pass rate, step execution counter, and average execution time
- Generation of failing_scenarios.txt for easy re-runs of failed tests

**Comment by hrcorval** [comment]
BehaveX is particularly well-suited for:
1. Large-scale projects with complex testing requirements
2. Teams that need detailed, customizable reporting capabilities
3. Scenarios where test management and execution control are crucial
4. Projects requiring advanced features like test muting, auto-retries, and dry runs
5. Environments where comprehensive insights into test execution metrics are valuable
6. Situations where easy integration of evidence (like screenshots) into test reports is necessary
BehaveX offers a more comprehensive solution and may be preferable when the additional features and detailed reporting justify the potential increase in complexity compared to a simpler parallel execution tool.
