### ISSUE TITLE
Missing background steps in the in the scenarios

### ISSUE THREAD

**Issue by TomaszKarski** [hrcorval/behavex#73]
I use the command:
`behavex -t @tag --parallel-processes 4 --parallel-scheme scenario -D market=DK --output-folder reports/DK`
and in HTML or JSON response, I can't find the background steps.

**Comment by hrcorval** [comment]
Hi @TomaszKarski, you can see the background steps in HTML report, by clicking on the "(show background)" link inside each feature, in scenarios header:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/7736350/234617042-4bd7a0aa-47c5-4a01-8e71-51358e5d9bd6.png">

I hope it helps :)
