### ISSUE TITLE
how to run scenario outline and scenario in parallel

### ISSUE THREAD

**Issue by praveenkannan1987** [hrcorval/behavex#74]
Questions
1) Can you tell me how run to scenario outline in parallel using behavex
2) Can you also tell me how to run scenario outline and scenario in parallel
for example scenario outline contains 3 user id and password. and one scenario

parallel process =4
i want run parallel 4 browser at time

**Comment by hrcorval** [comment]
Hi @praveenkannan1987, running scenario outlines in parallel is not supported by BehaveX yet, as we are trying not to impact the Behave logic in any way. As the scenario outline logic is managed by the Behave library, we are not being able yet to split the execution of that scenarios in multiple processes. 
At the moment, Behavex executes scenarios and features in parallel, but scenario outlines will run in serial mode inside a parallel process.
Regards.

**Comment by praveenkannan1987** [comment]
Thanks. will there be enhancement for scenario outline in the future ?

**Comment by hrcorval** [comment]
I hope so! As the solution would be to parse the scenario outline on the wrapper side, so We can get the individual scenarios slitted across parallel processes.

**Comment by korrapatisandhya** [comment]
Hi anibalinn, 
i am using selenium, python ,behave and behavex libraries in my project.
My project is about to execute same steps for multiple input dynamically through command line parameters in that case i choose the scenario outline in behavex to use but i am unable execute the examples of scenario outline parallelly please let me know is behavex support parallel execution of scenario outline if so kindly  provide me an example.

**Comment by hrcorval** [comment]
Hi @korrapatisandhya , running scenario outlines in parallel is something we are exhaustively doing at the moment. Please, update to the latest BehaveX version and ive it a try. This is working in both, feature and scenario parallel executions. 
Ee apologize if you had issues in v3.0.0.
I hope it helps.

Thanks!!
