### ISSUE TITLE
undefined status of a step is converted to failed status for a scenario

### ISSUE THREAD

**Issue by DeepakMehtaRepo** [hrcorval/behavex#8]
**Describe the bug**
If we have a step which is not defined yet the status of that step should be "undefined" or "pending" and all other steps followed by that should have status as "skipped". which works as expected. And the status of that scenario should be "undefined" or "pending" or "skipped" (expected). However the status is "failed" for such scenario (actual).

**To Reproduce**
1. Write a scenario and do not implement one of the step
2. run the scenario
3. validate the status of scenario in report
4. in report the status of this scenario should be  "undefined" or "pending" or "skipped". 

**Expected behavior**
In report the status of this scenario should be  "undefined" or "pending" or "skipped". 

**Screenshots**
Xml Report:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/97754499/153604249-e1685e34-abf4-4e1c-aea9-5abca3035d9a.png">

Html Report:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/97754499/153603632-661c6330-acc6-48cb-8333-51b15a04d9c0.png">

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [98.0.4758.82]

**Comment by anibalinn** [comment]
Hi @DeepakMehtaRepo, this is a bug, we will work on it and provide a new version with this fix

**Comment by anibalinn** [comment]
@DeepakMehtaRepo we have been reviewing this and we realized that, for the steps you indicated, it is correct to set the scenario as failed. This is the same behavior are in the "behave" framework. 
In case you have a scenario with undefined steps, you should tag it as @WIP (work in progress). This tag indicates the framework to do not run the scenario, and it will appear as "skipped".
