### ISSUE TITLE
runner: Ignores "other.features/some.feature" and uses always "features" directory

### ISSUE THREAD

**Issue by jenisys** [hrcorval/behavex#80]
**Describe the bug**
The runner seems to ignore the command-line args mostly and seems to run only `*.feature` files in a `features/` directory.

HINTS:
* If you provide `behavex` with a directory, it seems to use `*.feature` files from this directory (OK)
* If you provide `behavex` with one or more `*.feature` files, it seems to use `features/*.feature` files only (NOT_OK)

**To Reproduce**
1. Run `behavex more.features/some.feature`
2. Check if `behavex` tries to run feature-files from a collocated `features/` directory

**Expected behavior**
The user should have control which feature-files/feature-directories are used by the runner.

**Version Info:**
 - behavex v2.0.2 (current HEAD of repository)

**Comment by anibalinn** [comment]
Fix implemented in the upcoming release branch [release_2.0.3](https://github.com/hrcorval/behavex/tree/release_2.0.3)

**Comment by anibalinn** [comment]
Fix released in version 3.0.0: https://pypi.org/project/behavex/3.0.0/
branch [release_3.0.0](https://github.com/hrcorval/behavex/tree/release_3.0.0)
Thanks!
