### ISSUE TITLE
html.report: Stack traces are not really readable

### ISSUE THREAD

**Issue by jenisys** [hrcorval/behavex#81]
**Describe the bug**
If a scenario fails and a stack trace is shown in the HTML report, it is in nearly cases mostly unreadable.

REASONS:

* Textual output needs 80 columns and more
* Stack trace is confined to first "table column" on the left side. 
  The remaining text on the line that does not fit into the column-width is wrapped around make the lines indistinguishable/unreadable
* On a small screen (13inch / 15inch), this makes a stack trace really unreadable

**To Reproduce**
1. Run `behavex` with a feature-file that contains a failing scenario 
2. Inspect the stack trace in the HTML report afterwards
3. If you use a wide screen, like 27inch, you probably need to constrain the web browser to use only half of the screen

**Expected behavior**

* Stack traces should be readable
* IDEA: May be the column part could be extended for the stack trace to use the complete table width (info from other columns is already shown above the stack trace)
* IDEA: May be use a scrollable section/element (at least)

**Version Info:**
 - behavex v2.0.2 (current HEAD of repository)

**Comment by hrcorval** [comment]
Fix implemented in brach [release_2.0.2](https://github.com/hrcorval/behavex/tree/release_2.0.2)
A scrollbar will be shown for long gherkin steps and failure messages.

**Comment by anibalinn** [comment]
Fix released in version 3.0.0: https://pypi.org/project/behavex/3.0.0/
branch [release_3.0.0](https://github.com/hrcorval/behavex/tree/release_3.0.0)
Thanks!
