### ISSUE TITLE
Display Input Folder location or RegEx that we have supplied

### ISSUE THREAD

**Issue by qarampage** [hrcorval/behavex#88]
**Is your feature request related to a problem? Please describe.**
1. Display Input Folder Location / RegEx whichever available 

**Describe the solution you'd like**
In the summary table when it started the execution, display the INPUT FOLDER LOCATION or REGEX that is being used. which ever is available 

**Describe alternatives you've considered**
There is no alternative as such. We already have a RegEx to filter the Feature file 

**Additional context**
I am referring to the summary table that displays in the beginning when behaveX starts

**Comment by anibalinn** [comment]
Fixed in upcoming release branch [release_2.0.3](https://github.com/hrcorval/behavex/tree/release_2.0.3)
Thanks a lot!

**Comment by qarampage** [comment]
Hi,
The package Release 2.0.2 (via PR #75) is not yet available in pypi.org. could you please publish that as well.
Thanks

**Comment by hrcorval** [comment]
Fix released in version 3.0.0 :)
Thanks!
