### ISSUE TITLE
Files not getting filtered by the include RegEx

### ISSUE THREAD

**Issue by qarampage** [hrcorval/behavex#89]
**Describe the bug**
I used the Regex but it didn't filter the feature files 

**To Reproduce**
Create a folder called FINAL inside /features
add few feature files with prefix a par_
<img width="355" alt="image" src="https://github.com/hrcorval/behavex/assets/16265665/8dcf0603-1275-4dbc-b89c-11c0daa96508">

Execute the command 
<img width="691" alt="image" src="https://github.com/hrcorval/behavex/assets/16265665/1da35149-665b-457f-87b3-0dd43588201f">

**Expected behavior**
These files should have been executed. only 1 file would get skipped. but remaining two files matching the Regex should work

**Screenshots**
|--------------------| ------------------------------------------------------------|
|ENV. VARIABLE       | VALUE                                                       |
|--------------------| ------------------------------------------------------------|
|HOME                | /Users/qarampage                                            |
|CONFIG              | /Users/qarampage/venv/lib/python3.11/site-packages/behavex/conf_behavex.cfg|
|OUTPUT              | /Users/qarampage/output|
|TAGS                | None                                                        |
|PARALLEL_SCHEME     | scenario                                                    |
|PARALLEL_PROCESSES  | 2                                                           |
|TEMP                | /Users/qarampage/output/temp|
|LOGS                | /Users/qarampage/output/outputs/logs|
|LOGGING_LEVEL       | INFO                                                        |
|--------------------| ------------------------------------------------------------|
************************************************************
Running parallel scenarios

************************************************************

Total execution time:   0.2s
Exit code: 0

Also, I have tried this command , even these don't  work.
$ behavex -ip features-i ^par_L[\w-]+\.feature$  --parallel-processes 2  --parallel-scheme scenario
$ behavex -ip features -i par_L[\w-]+\.feature  --parallel-processes 2  --parallel-scheme scenario

Below command generated 0 Scenarios to execute 
$ behavex -ip ./features -i ^par_L[\w-]+\.feature$  --parallel-processes 2  --parallel-scheme scenario

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version: 114 

**Smartphone (please complete the following information):**
**Not applicable**

**Additional context**
N/A

**Comment by hrcorval** [comment]
Hi @qarampage , it seems that you need to escape the square brackets. Otherwise, they will be considered as part of the feature filename:
 behavex -ip features-i par_L\[\w-\]+.feature --parallel-processes 2 --parallel-scheme scenario
