### ISSUE TITLE
Json and HTML Report - Feature status is failed even though all steps in scenario got passed

### ISSUE THREAD

**Issue by Sujay008** [hrcorval/behavex#91]
** Description **
All the steps in the scenario are passed, however, feature status got failed. 

**To Reproduce**
1. We have a repository with a bunch of tests
2. We have a retry happening in different stage in Jenkins 
3. So, in the retry report generated Json file, we observed status of scenarios and status of all steps got passed.. However, we see the feature status as failed.. 

As HTML is derived from Json report, feature is showing as red eventhough all scenarios passed.

Note : We are running the tests at feature level

**Comment by anibalinn** [comment]
Hi @Sujay008 . Sadly, all retries happening in separate BehaveX executions will generate independent output assets. So, if the build server registered a failing execution from the initial test run, no matter if it was in green in the retry, the build server will show it as failed.

**Comment by Sujay008** [comment]
@anibalinn  - Its not happening for all scenarios in re-try. only happening for only few scenarios.. For example in the initial attempt 10 scenarios failed and during re-try 5 passed - Now, out of 5 only 2 features showing as failed and remaining 3 shows as passed..
