### ISSUE TITLE
Screenshots Not Added in Report During GitHub Action Run (but Added Locally)

### ISSUE THREAD

**Issue by Ajithkumaremis** [hrcorval/behavex#92]
**Describe the bug**
       During the execution of the GitHub Actions workflow, the screenshots are not being added to the report, even though they are added successfully when running locally. This discrepancy is causing difficulties in troubleshooting and understanding the test results.
       Note: below code was added in after step:
                "context.driver.save_screenshot(context.evidence_path + './'+ current_scenario_name +'.png')"

**To Reproduce**

**Expected behavior**
The report generated by GitHub Actions should include the same screenshots as the local report

**To Reproduce**
1.Set up the GitHub Actions workflow to run automated tests that generate screenshots.
2.Run the GitHub Actions workflow and observe the report generation process.
3.Compare the generated report with the local report, which includes the expected screenshots.

**Expected behavior**

**Screenshots**
Local report:
![image](https://github.com/hrcorval/behavex/assets/137084900/e9d04a33-6036-48df-90fd-024e46502476)

Github report:
![image](https://github.com/hrcorval/behavex/assets/137084900/cb488552-0853-4298-bf30-441d74e10be9)

**Desktop (please complete the following information):**
 - OS: [ Linux]
 - Browser :[chrome]

.

**Comment by TugaInVegas** [comment]
Hey @Ajithkumaremis , do you mind sharing how you got the local screenshots to work for you? I've been trying to find info on this, but havent really been able to.

**Comment by hrcorval** [comment]
Hi @Ajithkumaremis, @TugaInVegas. Finally, We have a draft library that allows you to attach screenshots to the HTML report. It is very easy to use.
Please take a look at the following: https://test.pypi.org/project/behavex-images/3.0.4/
We are already using it in some other projects and we find it to be very useful. 
Any feedback on that one will help us a lot.
I hope it helps :)
