### ISSUE TITLE
Need more information in the  HTML Report

### ISSUE THREAD

**Issue by qarampage** [hrcorval/behavex#94]
Hi Team,

1. Need Date Time info on the HTML report. I the snapshot below it doesn't have that information next to Test Report in the Black ribbon
     - Start Date time of Execution
     - End Date time of Execution
     - Duration in hrs / min whichever is relevant. If duration is less than 60 min it should in min:ss , else if duration is 60+ then in hh:mm:ss
<img width="1971" alt="image" src="https://github.com/hrcorval/behavex/assets/16265665/adc94fe5-2157-4f10-9e42-def1433809a6">

2. Need duration in sec or min for each Step , that would really help narrow down the time taking steps of the scenario

3. Also in the above snapshot , if you notice that when tags is selected as ALL , it shows the bottom aggregation info with TOTAL .But when you select any other TAG it doesn't show the TOTAL bottom row  (missing TOTAL row in the snapshot below)
<img width="2018" alt="image" src="https://github.com/hrcorval/behavex/assets/16265665/e3a3a715-c735-4bff-a34a-5eae2a34faca">

**Comment by anibalinn** [comment]
Hi @qarampage, we will work on adding the missing information to the report. Most probably this will be available in next release.
Thanks!

**Comment by hrcorval** [comment]
Hi @qarampage , We have released a new library version (v4.0.2) with the requested improvements (among multiple other enhancements/fixes):
![image](https://github.com/user-attachments/assets/0d658813-618a-487e-9620-e05fa07c9dc7)

You can see the information in the upper right side of the execution report.
Also, In case you need to provide additional info, you can set the ENVIRONMENT_DETAILS environment variable, with comma separated strings that will be parsed and shown in the tooltip (as you can see in the screenshot).
Regarding issues 2 and 3, we will leave them as improvements for upcoming versions.
Thanks a lot for reporting that improvements!
I hope it helps
